/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CertificateRegistryInterface extends Interface {
    getFunction(nameOrSignature: "certificateIdAt" | "getCertificate" | "owner" | "registerCertificate" | "totalCertificates" | "updateStatus" | "verifyHash"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CertificateRegistered" | "CertificateStatusUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'certificateIdAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCertificate', values: [string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerCertificate', values: [string, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalCertificates', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateStatus', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'verifyHash', values: [string, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'certificateIdAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalCertificates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyHash', data: BytesLike): Result;
  }

  
    export namespace CertificateRegisteredEvent {
      export type InputTuple = [certificateId: string, dataHash: BytesLike, status: BigNumberish];
      export type OutputTuple = [certificateId: string, dataHash: string, status: bigint];
      export interface OutputObject {certificateId: string, dataHash: string, status: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CertificateStatusUpdatedEvent {
      export type InputTuple = [certificateId: string, newStatus: BigNumberish];
      export type OutputTuple = [certificateId: string, newStatus: bigint];
      export interface OutputObject {certificateId: string, newStatus: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CertificateRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): CertificateRegistry;
    waitForDeployment(): Promise<this>;

    interface: CertificateRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    certificateIdAt: TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getCertificate: TypedContractMethod<
      [certificateId: string, ],
      [[string, bigint, bigint, string, boolean] & {dataHash: string, status: bigint, recordedAt: bigint, recordedBy: string, exists: boolean }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerCertificate: TypedContractMethod<
      [certificateId: string, dataHash: BytesLike, status: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    totalCertificates: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    updateStatus: TypedContractMethod<
      [certificateId: string, newStatus: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    verifyHash: TypedContractMethod<
      [certificateId: string, dataHash: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'certificateIdAt'): TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getCertificate'): TypedContractMethod<
      [certificateId: string, ],
      [[string, bigint, bigint, string, boolean] & {dataHash: string, status: bigint, recordedAt: bigint, recordedBy: string, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerCertificate'): TypedContractMethod<
      [certificateId: string, dataHash: BytesLike, status: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalCertificates'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'updateStatus'): TypedContractMethod<
      [certificateId: string, newStatus: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyHash'): TypedContractMethod<
      [certificateId: string, dataHash: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'CertificateRegistered'): TypedContractEvent<CertificateRegisteredEvent.InputTuple, CertificateRegisteredEvent.OutputTuple, CertificateRegisteredEvent.OutputObject>;
getEvent(key: 'CertificateStatusUpdated'): TypedContractEvent<CertificateStatusUpdatedEvent.InputTuple, CertificateStatusUpdatedEvent.OutputTuple, CertificateStatusUpdatedEvent.OutputObject>;

    filters: {
      
      'CertificateRegistered(string,bytes32,uint8)': TypedContractEvent<CertificateRegisteredEvent.InputTuple, CertificateRegisteredEvent.OutputTuple, CertificateRegisteredEvent.OutputObject>;
      CertificateRegistered: TypedContractEvent<CertificateRegisteredEvent.InputTuple, CertificateRegisteredEvent.OutputTuple, CertificateRegisteredEvent.OutputObject>;
    

      'CertificateStatusUpdated(string,uint8)': TypedContractEvent<CertificateStatusUpdatedEvent.InputTuple, CertificateStatusUpdatedEvent.OutputTuple, CertificateStatusUpdatedEvent.OutputObject>;
      CertificateStatusUpdated: TypedContractEvent<CertificateStatusUpdatedEvent.InputTuple, CertificateStatusUpdatedEvent.OutputTuple, CertificateStatusUpdatedEvent.OutputObject>;
    
    };
  }